# Use root/example as user/password credentials
version: '3.7'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: shawang
    volumes:
      - /home/shawang/docker/volumes/datadir/mysql/ms:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080
